# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task: go:test
    silent: true

  go:test:
    cmds:
      - gotest ./...

  go:test:table:
    cmds:
      - set -o pipefail && go test -cover  ./... -json | tparse

  go:tidy:
    cmds:
      - go mod tidy
